config/routes.rb
Rails.application.routes.draw do
  root "home#dashboard"
  resources :products do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :movements
    validates :name, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def dashboard
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def index
      @products = Product.all
    end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)
      if @product.save
        redirect_to @product, notice: 'Se ha creado el producto correctamente.'
      else
        flash[:notice] = 'Ha ocurrido un error al crear el producto.'
        render :new, status: :unprocessable_entity
      end
    end

    def show
      @product = Product.find(params[:id])
    end

    def edit
      @product = Product.find(params[:id])
    end

    def update
      @product = Product.find(params[:id])
      if @product.update(product_params)
        redirect_to @product, notice: 'Se actualizó el producto correctamente'
      else
        render :edit
      end
    end

    def destroy
      @product = Product.find(params[:id])
      @product.delete

      respond_to do |format|
        format.html { redirect_to products_url, notice: "El producto se elimino correctamente." }
        format.json { head :no_content}
      end
    end

    private
    def product_params
      params.require(:product).permit(:name, :description, :reference, :capacitaciones, :cargo)
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/dashboard.html.erb
 <div class="row">
  <div class="col-lg-6">
    <div class="card" style="padding: 20px">
      <h1>App de gestion de Empleados</h1>
      <p>Aqui podras encontrar la lista de los empleados su historia laboral y profesion</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mi Gestion de empleados</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag asset_path('system-settings-svgrepo-com.svg') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body id="page-top">
    <div id="wrapper">
      <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
          <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
          </div>
          <div class="sidebar-brand-text mx-3">Mi App</div>
        </a>
        <hr class="sidebar-divider my-0">
        <li class="nav-item">
          <a class="nav-link" href="/">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
          </a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider">
        <li class="nav-item">
          <a class="nav-link" href="<%= products_path %>">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Productos</span>
          </a>
        </li>
      </ul>
      <!-- End of Sidebar -->
      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
          <!-- Topbar -->
          <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
            <!-- Sidebar Toggle (Topbar) -->
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
              <i class="fa fa-bars"></i>
            </button>
          </nav>
          <!-- End of Topbar -->
          <!-- Begin Page Content -->
          <div class="container-fluid">
            <!-- Page Heading -->
            <%= yield %>
          </div>
          <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->
        <!-- Footer -->
        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; Facu6M Website 2023</span>
            </div>
          </div>
        </footer>
        <!-- End of Footer -->
      </div>
      <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
  </body>
</html>

app/views/products/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card p-5">
      <%= form_with model: @product do |f| %>
        <% if @product.errors.any? %>
          <div class="alert alert-danger">
            <ul>
              <% @product.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :name, "Nombre" %>
          <%= f.text_field :name, class: "form-control", placeholder: 'Juan' %>
        </div>
        <div class="form-group">
          <%= f.label :reference, "Profesion" %>
          <%= f.text_field :reference, class: "form-control", placeholder: 'Arquitecto' %>
        </div>
        <div class="form-group">
          <%= f.label :description, "Historial laboral" %>
          <%= f.text_area :description, class: "form-control", placeholder: 'Trabajo - empresa - año' %>
        </div>
        <div class="form-group">
          <%= f.label :capacitaciones, "Capacitaciones" %>
          <%= f.text_area :capacitaciones, class: "form-control", placeholder: 'Capacitacion - empresa - año' %>
        </div>
        <div class="form-group">
          <%= f.label :cargo, "Cargo-Dependencia" %>
          <%= f.text_area :cargo, class: "form-control", placeholder: 'cargo - dependencia' %>
        </div>
        <div class="form-group">
          <%= f.submit "Enviar", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editar empleado existente</h1>
<a class="btn btn-primary" href="<%= product_path(@product) %>">Regresar al empleado</a>
<%= render 'form' %>

app/views/products/index.html.erb
<h1>Listado de empleados</h1>
<a href="<%= new_product_path %>" class="btn btn-primary btn-icon-split">
  <span class="icon text-white-50">
      <i class="fas fa-flag"></i>
  </span>
  <span class="text">Crear empleado</span>
</a>
<br><br>
<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Nombre</th>
      <th>Profesion</th>
      <th>Historial</th>
      <th>Acciones</th>
  </thead>
  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td><%= product.id %></td>
      <td><%= product.name %></td>
      <td><%= product.reference %></td>
      <td><%= product.description %></td>
      <td><%= link_to "Detalles", product_path(product), class: 'btn btn-primary' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>Crear nuevo producto</h1>

<%= render 'form', product: @product %>

<div>
<%= link_to 'Regresar al listado de productos', products_path, class: "btn btn-primary" %>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Detalles del Empleado</h1>
    <%= link_to "Regresar al listado de productos", products_path, class: 'btn btn-primary' %>
    <%= link_to "Editar", edit_product_path(@product), class: 'btn btn-primary' %>
    <div class="card" style="margin-top: 20px;">
      <table class="table">
        <tr>
          <td><b>Nombre del Empleado:</b></td>
          <td><%= @product.name %></td>
        </tr>
        <tr>
          <td><b>Profesion:</b></td>
          <td><%= @product.reference %></td>
        </tr>
        <tr>
          <td><b>Historial Laboral:</b></td>
          <td><%= @product.description %></td>
        </tr>
        <tr>
          <td><b>Capacitaciones:</b></td>
          <td><%= @product.capacitaciones %></td>
        </tr>
        <tr>
          <td><b>Cargo-Dependencia:</b></td>
          <td><%= @product.cargo %></td>
        </tr>
        <tr>
          <td><b>Fecha de creación:</b></td>
          <td><%= @product.created_at %></td>
        </tr>
        <tr>
          <td><b>Fecha de actualización:</b></td>
          <td><%= @product.updated_at %></td>
        </tr>
      </table>
    </div>
  </div>
</div>
<br>
     <%= button_to "Borrar producto", @product, method: :delete, class: "btn btn-danger"%>